import pyautogui, time, colorama, os
from colorama import Fore, Back, Style, init

init(autoreset=True)


def pantalla(): 
    if os.name == "posix":
         os.system ("clear")
    elif os.name == "ce" or os.name == "nt" or os.name == "dos":
         os.system ("cls")

def WhatsAppWeb_spam():
    cantidad1 = 0
    print("")
    print(Fore.GREEN +" __          __      __          ________ ____", end="")
    print(Fore.YELLOW +"     _____ _____        __  __ ")
    print(Fore.GREEN +" \ \        / /\     \ \        / /  ____|  _ \ ", end="")
    print(Fore.YELLOW +"  / ____|  __ \ /\   |  \/  |")
    print(Fore.GREEN +"  \ \  /\  / /  \     \ \  /\  / /| |__  | |_) |", end="")
    print(Fore.YELLOW +" | (___ | |__) /  \  | \  / |",)
    print(Fore.GREEN +"   \ \/  \/ / /\ \     \ \/  \/ / |  __| |  _ < ", end="")
    print(Fore.YELLOW +"  \___ \|  ___/ /\ \ | |\/| |")
    print(Fore.GREEN +"    \  /\  / ____ \     \  /\  /  | |____| |_) |", end="")
    print(Fore.YELLOW +"  ____) | |  / ____ \| |  | |")
    print(Fore.GREEN +"     \/  \/_/    \_\     \/  \/   |______|____/  ", end="")
    print(Fore.YELLOW +"|_____/|_| /_/    \_\_|  |_|", end="")
    print(Fore.LIGHTCYAN_EX +" 1.0")       
    print("")
    print("")
    print(Fore.YELLOW +"   [", end="")
    print(Fore.MAGENTA +"*", end="")
    print(Fore.YELLOW +"]", end="")
    print(Fore.LIGHTCYAN_EX +" Hecho por wrrulos")
    print(Fore.YELLOW +"   [", end="")
    print(Fore.MAGENTA +"*", end="")
    print(Fore.YELLOW +"]", end="")
    print(Fore.LIGHTCYAN_EX +" www.github.com/wrrulos")
    print("")
    print("")
    print(Fore.YELLOW +" [", end="")
    print(Fore.MAGENTA +"*", end="")
    print(Fore.YELLOW +"]", end="")
    mensaje = (input(Fore.LIGHTCYAN_EX +" Escribe el contenido del mensaje: "))   
    print("")
    print(Fore.YELLOW +" [", end="")
    print(Fore.MAGENTA +"*", end="")
    print(Fore.YELLOW +"]", end="")
    cantidad2 = int(input(Fore.LIGHTCYAN_EX +" Cantidad de mensajes: "))       
    print("")
    print(Fore.YELLOW +" [", end="")
    print(Fore.GREEN +"OK", end="")
    print(Fore.YELLOW +"]", end="")
    print(Fore.LIGHTCYAN_EX +" El spam va a empezar en 5 segundos") 
    time.sleep(5)
    pantalla()
    print(Fore.MAGENTA +"  _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ ")
    print(Fore.MAGENTA +" |_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|")
    print(Fore.MAGENTA +" | |                                                                               | |")
    print(Fore.MAGENTA +" | |                                                                               | |")
    print(Fore.MAGENTA +" | |                                                                               | |")
    print(Fore.MAGENTA +" | |                                                                               | |")
    print(Fore.MAGENTA +" |_|", end="")
    print(Fore.GREEN +"   __        ___    __        _______ ____       ____  ____   _    __  __      ", end="")
    print(Fore.MAGENTA +"|_|")
    print(Fore.MAGENTA +" | |", end="")
    print(Fore.GREEN +"   \ \      / / \   \ \      / / ____| __ )     / ___||  _ \ / \  |  \/  |     ", end="")
    print(Fore.MAGENTA +"| |")
    print(Fore.MAGENTA +" | |", end="")
    print(Fore.GREEN +"    \ \ /\ / / _ \   \ \ /\ / /|  _| |  _ \ ____\___ \| |_) / _ \ | |\/| |     ", end="")
    print(Fore.MAGENTA +"| |")
    print(Fore.MAGENTA +" | |", end="")
    print(Fore.GREEN +"     \ V  V / ___ \   \ V  V / | |___| |_) |_____|__) |  __/ ___ \| |  | |     ", end="")
    print(Fore.MAGENTA + "| |")
    print(Fore.MAGENTA +" | |", end="")
    print(Fore.GREEN + "      \_/\_/_/   \_\___\_/\_/  |_____|____/     |____/|_| /_/   \_\_|  |_|     ", end="")
    print(Fore.MAGENTA +"| |")
    print(Fore.MAGENTA +" |_|", end="")
    print(Fore.GREEN +"                  |_____|                                                      ", end="")
    print(Fore.MAGENTA +"|_|")
    print(Fore.MAGENTA +" | |                                                                               | |")
    print(Fore.MAGENTA +" | |", end="")
    print(Fore.RED +"                       CTRL + C", end="")
    print(Fore.YELLOW +" para detener el spam", end="")
    print(Fore.MAGENTA +"                           | |")
    print(Fore.MAGENTA +" | |                                                                               | |")
    print(Fore.MAGENTA +" | |___ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ _____ ___| |")
    print(Fore.MAGENTA +" |_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|_____|")  

    while True: 
        cantidad1 += 1
        pyautogui.typewrite(mensaje)
        pyautogui.press("enter") 

        if cantidad1 == cantidad2:
            break

pantalla()
WhatsAppWeb_spam()